### ISSUE TITLE
invalid `mv` invocation in stability matrix ebuild

### ISSUE THREAD

**Issue by West14** [arran4/arrans_overlay#12]
https://github.com/arran4/arrans_overlay/blob/a9de6d92f626e6ced0e40d7e085c71c5a407f239/app-misc/stability-matrix-appimage/stability-matrix-appimage-2.12.0.ebuild#L25

Please check this, it's broken at least for a month. Thank you.

**Comment by arran4** [comment]
Understood. Thanks. I use it myself (a lot of the stuff here I wrote an ebuild to try it.)

It's probably a result of the generation. I will likely fix this today, or this weekend.

Feel free to log as many issues as soon as you like the future too.

**Comment by arran4** [comment]
![image](https://github.com/user-attachments/assets/8c226b2a-3b1f-4fe9-8ae4-7ef9e0531bbd)

Going to delete the older ebuilds and regenerate.

**Comment by arran4** [comment]
Oh Sorry auto closed...

Feel free to reopen if this isn't resolved. This should re-generate correctly over the next day. I will keep an eye on it. I will be back at my computer to properly verify this by then too!

**Comment by West14** [comment]
nice! thank you
![image](https://github.com/user-attachments/assets/d20deb63-107c-44e5-9f33-d0b657f9e4d1)
