### ISSUE TITLE
app-misc/go-appimage-appimage-0.0.194: Install failed

### ISSUE THREAD

**Issue by JohnTheCoolingFan** [arran4/arrans_overlay#4]
```
>>> Install app-misc/go-appimage-appimage-0.0.194 into /var/tmp/portage/app-misc/go-appimage-appimage-0.0.194/image
!!! doexe: appimaged.AppImage does not exist
```

Checked what is in the workdir, and it's just `0.AppImage`

**Comment by arran4** [comment]
Yeah this doesn't look right. I'll have some time tomorrow to look into it.

**Comment by arran4** [comment]
Okay I wasn't able to today, tomorrow. Sorry. I have a fairly good idea I suspect it's related to:
https://github.com/gentoo-mirror/arrans-overlay/pull/1

**Comment by arran4** [comment]
Long term fix for this:

https://github.com/arran4/arrans_overlay_workflow_builder/issues/4

@JohnTheCoolingFan  FYI I have issues with the way the appimage repos work which require work arounds

**Comment by arran4** [comment]
Ah, so this was handwritten one it seems. So workflow builder isn't relevant.

**Comment by arran4** [comment]
I pushed a fix [9bda522](https://github.com/arran4/arrans_overlay/commit/9bda5225168450422e3885a7242635dc4efc0162) it should take 15ish minutes to get into the gentoo mirror. I will test it soon.

**Comment by arran4** [comment]
Okay try now: 838c252d478ea665e9abe2518c640b84eaec16f5 seems to fix it on my end:

![image](https://github.com/user-attachments/assets/0818ae29-c5c8-4361-ad20-5e1aba23f1ee)

@JohnTheCoolingFan

**Comment by JohnTheCoolingFan** [comment]
Yep, works for me now

**Comment by JohnTheCoolingFan** [comment]
Hmm, I've hoped this package would also provide systemd services and such. Looks like if I want this to not be an appimage and provide systemd services I'll have to make my own ebuild. Thanks for maintaining this anyway!

**Comment by arran4** [comment]
Yep sorry, I probably should have only included the executable which was relevant. Sorry. I am attempting to build a builder for my workflows to build these ebuilds, however it's complex. I haven't started the systemd stage yet. I mostly built this for building appimages rather than running them.

If you link me here to your completed version I can incorporate it, later down the track. Sorry for the confusion. -- Happy to take PRs too.

**Comment by arran4** [comment]
I've opened https://github.com/arran4/arrans_overlay/issues/6 for myself
