### ISSUE TITLE
dev-ml category misused

### ISSUE THREAD

**Issue by xgqt** [arran4/arrans_overlay#8]
Hello!

Thanks for the overlay of may interesting packages.

I've filed this issue because you have put AI-learning packages into the `dev-ml` category.
`dev-ml` is traditionally for OCaml packages as defined in the ::gentoo repo. [1]

To avoid confusion please migrate to `dev-util` or create own category like `ai-app`.
I'd prefer it to be new category for ebuilds residing in `dev-ml` in Your repo currently.

In order to add a custom category list it in the `profiles/categories` [2] file and add a `metadata.xml` file to the category root. 

Thanks in advance!

[1] https://github.com/gentoo/gentoo/blob/master/dev-ml/metadata.xml
[2] https://github.com/gentoo/gentoo/blob/master/profiles/categories

**Comment by arran4** [comment]
Thanks I will address this soon. Let me know if it's a matter of urgency though

**Comment by xgqt** [comment]
No, this is not urgent to resolve.

**Comment by arran4** [comment]
Should be resolved now. I moved it to app-misc as I'm reluctant to create new categories at the moment.

**Comment by arran4** [comment]
Looks like I have to resolve a generation issue with a couple of them too.

**Comment by xgqt** [comment]
Thanks!
